AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates an EC2 instance with a customized AMI.
Parameters:
  ImageId:
    Description: Image ID of the Amazon Machine Image (AMI) to use for the instance
    Type: AWS::EC2::Image::Id
    ConstraintDescription: must be a valid EC2 Image ID.

Resources:
  CustomImageKeyPair:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: custom-new-key-pair
  CustomImageInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.small
      SecurityGroups:
        - !Ref CustomImageSecurityGroup
      KeyName: !Ref CustomImageKeyPair
  CustomImageSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  CustomImageInstancePublicDnsName:
    Description: URL for newly created LAMP stack
    Value: !GetAtt CustomImageInstance.PublicDnsName
  CustomImageKeyPaidId:
    Description: KeyPair ID of the newly created EC2 instance
    Value: !GetAtt CustomImageKeyPair.KeyPairId
