AWSTemplateFormatVersion: "2010-09-09"
Description: "(Cloudfront-as-default-03) Simple CloudFront distribution with an S3 origin"

Parameters:
  S3BucketName:
    Type: String
    Default: Your S3 Bucket Name
    Description: Name of existing S3 bucket

Resources:
  S3BucketPolicyWithAOI:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}/*"

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Comment: "A simple distribution with an S3 origin"
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: "none"
            Headers:
              - "Origin"
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Sub "s3-origin-${S3BucketName}"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: "http1.1"
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub "${S3BucketName}.s3.amazonaws.com"
            Id: !Sub "s3-origin-${S3BucketName}"
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        PriceClass: "PriceClass_All"

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Access S3 bucket content only through CloudFront"

Outputs:
  S3BucketName:
    Description: "Bucket name"
    Value: !Ref S3BucketName
  CloudFrontDistribution:
    Description: "Id for our cloudfront distribution"
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: "Domain name for our cloudfront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
